### ISSUE TITLE
Invalidate results in SpatiotemporalAnalysis with options / partly

### ISSUE THREAD

**Issue by kathapand** [3dgeo-heidelberg/py4dgeo#161]
The temporal smoothing of the space time array takes quite long. It would be good to have the following options:

- use `invalidate_results()` with the option to keep the temporal smoothing (i.e. invalidate only seeds and objects of 4D-OBCs)
- invalidate results only from a certain timestamp (e.g. corresponding to the temporal window of smoothing). This makes sense because if we add the next epoch during monitoring, we don't want to run the full analysis again for the time series "archive"

**Comment by dokempf** [comment]
I will need to split this in two parts: The first is to make smoothed distances data a first class citizen that is stored in the archive as an intermediate result. The second is to allow partial invalidation which is quite an undertaking that we will need to target later.

**Comment by kathapand** [comment]
To the second: if the smoothing is done separately from the segmentation (run()), then the partial invalidation may not be required, because the smoothed distances are simply the stored m3c2/spacetime array values (if I am thinking correctly).

**Comment by dokempf** [comment]
Ah yes, I have forgotten about this part of your request. Partial runs still might be a thing - otherwise you e.g. perform region growing on seeds where you already know the results.
