### ISSUE TITLE
Images in documentation are not showing on readthedocs

### ISSUE THREAD

**Issue by kathapand** [3dgeo-heidelberg/py4dgeo#212]
**Problem**
Images in the documentation (e.g. https://github.com/3dgeo-heidelberg/py4dgeo/edit/main/README.md#-methods-provided-by-py4dgeo) are not showing on the compiled site on readthedocs (https://py4dgeo.readthedocs.io/en/latest/intro.html#methods-provided-by-py4dgeo).

**Solution**
Assumingly solved by putting image files in directory named `_static`, see https://github.com/readthedocs/readthedocs.org/issues/5709#issuecomment-1149041819. To be tested.

**Comment by dokempf** [comment]
I learned an alternative way of dealing with the situation lately, that also makes the images display on the PyPI project page: Use absolute URLs to Github, see e.g. here: https://github.com/parafields/parafields/commit/cc5055f2aac1b47597d76fa37300ac0c5a34c5e6

**Comment by kathapand** [comment]
Thanks! Nice solution.
I changed it to absolute URLs. Works for rendering in gitlab, I cannot yet verify it on readthedocs though.
