### ISSUE TITLE
How to call your library in C++ to calculate point cloud displacement with M3C2 algorithm

### ISSUE THREAD

**Issue by YangkoC** [3dgeo-heidelberg/py4dgeo#217]
I am a novice who just learned C++. I want to call your library in C++to use M3C2 to calculate the displacement of point cloud. I hope you can give me some help. Thank you very much.

**Comment by kathapand** [comment]
The library is open, so you may just integrate the code/functions in your own workflows. You may have a look at the documentation for the C++ API: https://py4dgeo.readthedocs.io/en/latest/cppapi.html
