### ISSUE TITLE
Error when using no seed sorting according to base algorithm

### ISSUE THREAD

**Issue by kathapand** [3dgeo-heidelberg/py4dgeo#237]
The customization of prioritizing seeds throws an error when implementing no sorting in the function following the base algorithm as implemented [here](https://github.com/3dgeo-heidelberg/py4dgeo/blob/main/src/py4dgeo/segmentation.py#L650):

**The code I am using:**
```
def sorting_criterion(seed):
    # do not perform seed sorting
    return lambda seed: 0.0

class MySorting(py4dgeo.RegionGrowingAlgorithm):
    def seed_sorting_scorefunction(self):
        return sorting_criterion
```

**The error:** `TypeError: '<' not supported between instances of 'function' and 'function'`

As the customization works with the [example of random sorting](https://py4dgeo.readthedocs.io/en/latest/4dobc-customization.html#Prioritizing-seeds), this may be a problem with the lambda function? Or some change in usage that needs to be considered - how would I implement no sorting?

**Comment by dokempf** [comment]
You built in one level of indirection too much. You are already defining a separate function `sorting_criterion` - it should return the score for the seed directly. In other words: The function already takes the role of the lambda.

You can fix this with one of the following (untested):

```python
def sorting_criterion(seed):
    # do not perform seed sorting
    return 0.0

class MySorting(py4dgeo.RegionGrowingAlgorithm):
    def seed_sorting_scorefunction(self):
        return sorting_criterion
```
or
```python
class MySorting(py4dgeo.RegionGrowingAlgorithm):
    def seed_sorting_scorefunction(self):
        return lambda seed: 0.0
```
Your version mixes these two into something where you end up sorting by functions.

**Comment by kathapand** [comment]
Understood - and your solution works perfectly. Thanks a lot!!
