### ISSUE TITLE
m3c2 returns the same distance value for every point

### ISSUE THREAD

**Issue by neilslat** [3dgeo-heidelberg/py4dgeo#360]
OS: Windows 11
Python version: 3.12
py4dgeo version: 0.6.0

Running the m3c2 demo example on a demo dataset and my own datasets (40mm spacing Lidar scans of a cliff face with known change) returns a list of distance values that are all the same. The array contains the correct number of values (1259042 points) but with all the same distance parameter. Running the same datasets in CloudCompare generates the expected output with different distance values for each point.   

**Array analysis for the py4dgeo M3c2:**

Median M3C2 distances: -0.008350 m
Std. dev. of M3C2 distances: 0.000000 m
First 10 distance values:
[-0.00834995 -0.00834995 -0.00834995 -0.00834995 -0.00834995 -0.00834995
 -0.00834995 -0.00834995 -0.00834995 -0.00834995]

distance min:
-0.008349954578438457
distance max:
-0.008349954578438457
no of distances in array:
1259043

**m3c2 is parameterised with the following:**

m3c2 = py4dgeo.CloudCompareM3C2(
    epochs=(epoch1, epoch2),
    corepoints=corepoints,
    normal_radii=(0.5,),
    cyl_radii=(0.12,),
    max_distance=(5.0),
)

**Comment by kathapand** [comment]
Dear @neilslat ,
thank you for reporting this! Actually, we have recently observed a similar behavior in one case of constructing a SpatiotemporalAnalysis object. We are looking for the cause and currently suspect it is related to a Numpy version update. 
Could you let us know which version of Numpy you were using?
You may even give it a try to downgrade Numpy: `python -m pip install "numpy<2"`
We are happy about any report if this influences your results.
If possible, you may also share the script and data you are using - feel free to reach out to my mail adress if not publicly sharable (k.anders at tum.de).

**Comment by neilslat** [comment]
Great, thanks for the fast reply. I am using numpy version 2.1.3 but will try rolling back now and let you know what happens.

**Comment by neilslat** [comment]
Ok, so rolling back to numpy version 1.26.4 seems to have made a difference and I am now getting a different value for each point. I will export the points with distances and cross check with CloudCompare.

**Comment by neilslat** [comment]
Hi @kathapand I just exported the data and compared to CloudCompare and everything looks good. Thanks for the help and please let me know if there is any more testing I can do to help fix the issue.

**Comment by dokempf** [comment]
@neilslat Could you check whether the problem persists on the `bump-pybind` branch. This is my first guess on where things could go wrong with numpy 2, but without a setup for reproduction, I cannot verify myself.

**Comment by neilslat** [comment]
Hi Dominic, I am not currently building the code from source but installing  v0.6.0 current release through pip.

**Comment by neilslat** [comment]
Hi @dokempf , I tested the build here: https://github.com/3dgeo-heidelberg/py4dgeo/tree/bump-pybind

the issue is not present in this build using numpy version 2.1.3 and the output is the same as release version 0.6.0 with numpy version 1.26.4. Thanks

**Comment by dokempf** [comment]
Thanks for checking! I will fix this on the `main` branch and will create a bugfix release soon.
